import React from 'react';
import { Code, Lightbulb, Users, Zap } from 'lucide-react';

const About = () => {
  const highlights = [
    {
      icon: Code,
      title: 'Clean Code',
      description: 'Writing maintainable, scalable code that follows best practices'
    },
    {
      icon: Lightbulb,
      title: 'Problem Solver',
      description: 'Turning complex challenges into elegant, user-friendly solutions'
    },
    {
      icon: Users,
      title: 'Team Player',
      description: 'Collaborating effectively with cross-functional teams'
    },
    {
      icon: Zap,
      title: 'Fast Learner',
      description: 'Quickly adapting to new technologies and frameworks'
    }
  ];

  return (
    <section id="about" className="py-20 bg-gray-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            About Me
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Passionate developer with a love for creating impactful digital experiences
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <p className="text-gray-300 text-lg leading-relaxed">
              I'm a passionate junior full-stack developer with hands-on experience in web development 
              through my 5-month internship as a Web Developer. During this time, I contributed to 
              developing an innovative Autogenerated Schedule System that intelligently selects the 
              best options for students based on date, time, teacher availability, room capacity, and sections.
            </p>
            
            <p className="text-gray-300 text-lg leading-relaxed">
              I have solid experience with HTML5, PHP, SQL, and MySQL, and I'm currently expanding 
              my skillset by learning modern technologies like React, Node.js, and Tailwind CSS. 
              I use Git and GitHub for version control and am always eager to learn new technologies 
              that can improve my development skills.
            </p>

            <div className="flex flex-wrap gap-3">
              <span className="px-4 py-2 bg-blue-600/20 text-blue-400 rounded-full text-sm">
                HTML5
              </span>
              <span className="px-4 py-2 bg-blue-600/20 text-blue-400 rounded-full text-sm">
                PHP
              </span>
              <span className="px-4 py-2 bg-blue-600/20 text-blue-400 rounded-full text-sm">
                MySQL
              </span>
              <span className="px-4 py-2 bg-blue-600/20 text-blue-400 rounded-full text-sm">
                Git/GitHub
              </span>
              <span className="px-4 py-2 bg-green-600/20 text-green-400 rounded-full text-sm">
                Learning: React
              </span>
              <span className="px-4 py-2 bg-green-600/20 text-green-400 rounded-full text-sm">
                Learning: Node.js
              </span>
            </div>
          </div>

          <div className="grid sm:grid-cols-2 gap-6">
            {highlights.map((item, index) => (
              <div
                key={index}
                className="bg-gray-800/50 backdrop-blur-sm p-6 rounded-xl border border-gray-700/50 hover:border-blue-500/50 transition-all duration-300 transform hover:scale-105"
              >
                <div className="w-12 h-12 bg-blue-600/20 rounded-lg flex items-center justify-center mb-4">
                  <item.icon className="text-blue-400" size={24} />
                </div>
                <h3 className="text-white font-semibold mb-2">{item.title}</h3>
                <p className="text-gray-400 text-sm">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;